# Generated by Django 4.1.3 on 2022-11-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('field_type', models.CharField(choices=[('String', 'string'), ('Number', 'number'), ('Integer', 'integer'), ('Boolean', 'boolean'), ('Object', 'object'), ('Array', 'array'), ('Date', 'date'), ('Time', 'time'), ('Datetime', 'datetime'), ('Year', 'year'), ('Duration', 'duration'), ('Geopoint', 'geopoint'), ('Any', 'any')], max_length=20)),
                ('format', models.CharField(max_length=100)),
                ('example', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
