# Generated by Django 4.1.3 on 2022-11-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
