# Generated by Django 4.1.3 on 2022-11-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0002_field_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100, null=True)),
                ('constraint', models.CharField(choices=[('String', 'string'), ('Numeric', 'numeric'), ('Collection', 'collection'), ('Temporal', 'temporal')], max_length=20)),
                ('required', models.BooleanField()),
                ('unique', models.BooleanField()),
                ('min_length', models.BigIntegerField()),
                ('max_length', models.BigIntegerField()),
                ('minimum', models.BigIntegerField()),
                ('maximum', models.BigIntegerField()),
                ('pattern', models.CharField(max_length=100)),
                ('enum', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='constraints',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.fieldconstraint'),
        ),
    ]
