# Generated by Django 4.1.3 on 2022-11-27 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0003_fieldconstraint_field_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('is_primary', models.BooleanField()),
                ('is_foreign', models.BooleanField()),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.field')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prototype.field')),
                ('foreign_keys', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='prototype.key')),
                ('primary_keys', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prototype.key')),
            ],
        ),
        migrations.AddField(
            model_name='key',
            name='foreign_table',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prototype.table'),
        ),
    ]
