# Generated by Django 4.1.3 on 2022-11-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0004_key_table_key_foreign_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='primary_keys',
            new_name='keys',
        ),
        migrations.RemoveField(
            model_name='table',
            name='foreign_keys',
        ),
    ]
