# Generated by Django 4.1.3 on 2022-11-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0005_rename_primary_keys_table_keys_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldconstraint',
            old_name='constraint',
            new_name='type',
        ),
    ]
