# Generated by Django 4.1.3 on 2022-11-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0007_alter_fieldconstraint_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(choices=[('Any', 'any')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='keys',
        ),
        migrations.AddField(
            model_name='table',
            name='constraints',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.tableconstraint'),
        ),
    ]
