# Generated by Django 4.1.3 on 2022-11-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0009_table_keys_alter_table_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
