# Generated by Django 4.1.3 on 2022-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0010_table_description_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_type',
        ),
        migrations.AddField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('String', 'string'), ('Number', 'number'), ('Integer', 'integer'), ('Boolean', 'boolean'), ('Object', 'object'), ('Array', 'array'), ('Date', 'date'), ('Time', 'time'), ('Datetime', 'datetime'), ('Year', 'year'), ('Duration', 'duration'), ('Geopoint', 'geopoint'), ('Expression', 'expression'), ('Any', 'any')], max_length=20, null=True),
        ),
    ]
