# Generated by Django 4.1.3 on 2022-11-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0011_remove_field_field_type_field_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='is_foreign',
        ),
        migrations.RemoveField(
            model_name='key',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='fieldconstraint',
            name='expression',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='type',
            field=models.CharField(choices=[('Primary', 'primary'), ('Foreign', 'foreign'), ('Common', 'common')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='enum',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='pattern',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='type',
            field=models.CharField(choices=[('String', 'string'), ('Numeric', 'numeric'), ('Collection', 'collection'), ('Temporal', 'temporal'), ('Expression', 'expression'), ('Any', 'any')], max_length=20),
        ),
    ]
