# Generated by Django 4.1.3 on 2022-11-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0012_remove_key_is_foreign_remove_key_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableconstraint',
            name='expression',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tableconstraint',
            name='type',
            field=models.CharField(choices=[('Expression', 'expression'), ('Any', 'any')], max_length=20),
        ),
    ]
