# Generated by Django 4.1.3 on 2022-11-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0013_tableconstraint_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='expression',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='type',
            field=models.CharField(choices=[('Primary', 'primary'), ('Foreign', 'foreign'), ('Set', 'set')], max_length=20, null=True),
        ),
    ]
