# Generated by Django 4.1.3 on 2022-11-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0016_field_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='subtype',
            field=models.CharField(choices=[('Email', 'email'), ('First Name', 'first name'), ('Last Name', 'last name'), ('Full Name', 'full name'), ('Postal Code', 'postal code'), ('Positive Integer', 'positive integer'), ('Negative Integer', 'negative integer')], max_length=50, null=True),
        ),
    ]
