# Generated by Django 4.1.3 on 2022-12-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0018_alter_field_description_alter_field_example_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='foreign_table',
        ),
        migrations.AlterField(
            model_name='field',
            name='constraints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.fieldconstraint'),
        ),
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='distribution',
            field=models.CharField(choices=[('Normal', 'normal'), ('Uniform', 'uniform'), ('Exponential', 'exponential'), ('Binomial', 'binomial'), ('Bernoulli', 'bernoulli'), ('Poisson', 'poisson'), ('Custom', 'custom'), ('None', 'none')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='example',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='expression',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='subtype',
            field=models.CharField(choices=[('Email', 'email'), ('First Name', 'first name'), ('Last Name', 'last name'), ('Full Name', 'full name'), ('Postal Code', 'postal code'), ('Positive Integer', 'positive integer'), ('Negative Integer', 'negative integer'), ('None', 'none')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='enum',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='expression',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='max_length',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='maximum',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='min_length',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='minimum',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='pattern',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='required',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldconstraint',
            name='unique',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='fields',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.field'),
        ),
        migrations.AlterField(
            model_name='key',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='constraints',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.tableconstraint'),
        ),
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='fields',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.field'),
        ),
        migrations.AlterField(
            model_name='table',
            name='keys',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prototype.key'),
        ),
        migrations.AlterField(
            model_name='tableconstraint',
            name='expression',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tableconstraint',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tableconstraint',
            name='type',
            field=models.CharField(blank=True, choices=[('Expression', 'expression'), ('Any', 'any')], max_length=20, null=True),
        ),
    ]
