# Generated by Django 4.1.3 on 2022-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0020_remove_table_fields_table_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='keys',
        ),
        migrations.AddField(
            model_name='table',
            name='keys',
            field=models.ManyToManyField(blank=True, null=True, to='prototype.key'),
        ),
    ]
