# Generated by Django 4.1.3 on 2022-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0021_remove_table_keys_table_keys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='constraints',
        ),
        migrations.AlterField(
            model_name='table',
            name='fields',
            field=models.ManyToManyField(blank=True, to='prototype.field'),
        ),
        migrations.AlterField(
            model_name='table',
            name='keys',
            field=models.ManyToManyField(blank=True, to='prototype.key'),
        ),
        migrations.AddField(
            model_name='table',
            name='constraints',
            field=models.ManyToManyField(blank=True, to='prototype.tableconstraint'),
        ),
    ]
