# Generated by Django 4.1.3 on 2023-01-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0026_field_author_fieldconstraint_author_key_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldconstraint',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
