# Generated by Django 4.1.3 on 2023-01-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0027_fieldconstraint_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconstraint',
            name='expression',
            field=models.TextField(blank=True, null=True),
        ),
    ]
