# Generated by Django 4.1.3 on 2023-01-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0028_alter_fieldconstraint_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='fieldconstraint',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tableconstraint',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
    ]
