# Generated by Django 4.1.3 on 2023-01-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0029_field_slug_fieldconstraint_slug_key_slug_table_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='type',
            field=models.CharField(choices=[('Primary', 'primary'), ('Foreign', 'foreign'), ('Group', 'group')], max_length=20, null=True),
        ),
    ]
