# Generated by Django 4.1.3 on 2023-01-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0034_rename_follow_follower_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='name',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='name',
            new_name='author',
        ),
    ]
