# Generated by Django 4.1.3 on 2023-01-30 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0035_rename_name_comment_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posted',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='removed',
        ),
        migrations.AddField(
            model_name='comment',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='follower',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
