# Generated by Django 4.1.3 on 2023-01-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prototype', '0036_rename_posted_comment_start_remove_comment_removed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='end',
            field=models.DateTimeField(null=True),
        ),
    ]
