# Generated by Django 4.1.3 on 2023-01-30 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prototype', '0037_alter_like_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='likes',
        ),
        migrations.AddField(
            model_name='table',
            name='likes',
            field=models.ManyToManyField(related_name='table_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
