# Generated by Django 4.1.3 on 2023-01-30 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prototype', '0038_remove_table_likes_table_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='followers',
        ),
        migrations.AlterField(
            model_name='table',
            name='likes',
            field=models.ManyToManyField(related_name='table_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
