# Generated by Django 4.1.3 on 2023-01-30 23:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prototype', '0039_remove_table_followers_alter_table_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='followers',
            field=models.ManyToManyField(related_name='table_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='table',
            name='likes',
            field=models.ManyToManyField(related_name='table_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
