# Generated by Django 4.1.3 on 2022-12-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='other',
        ),
    ]
